repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.0.0
    hooks:
    -   id: setup-cfg-fmt
